"""Provisioning: answers must become configuration, and stay safe doing it."""

from __future__ import annotations

import pytest

from drgb.bridge import request_crossing
from drgb.envelope import load_envelope
from drgb.ledger import Ledger
from drgb.provision import (MONEY_IRREVERSIBLE, UNIVERSALLY_BARRED,
                            build_envelope_yaml, provision)


class _Lane:
    def __init__(self, name, eligible=True):
        self.name, self.ceiling_eligible = name, eligible


class _Scope:
    def __init__(self, lanes):
        self.lanes = lanes


SCOPE = _Scope([_Lane("AVARA 2.0"), _Lane("operator-brain"),
                _Lane("dark-lane", False)])
ANSWERS = {"money_lanes": "AVARA 2.0", "braid_sharing": "share_attributed"}


def _load(tmp_path, scope=SCOPE, answers=ANSWERS):
    path = provision(scope=scope, answers=answers,
                     out_path=tmp_path / "generated.yaml")
    return load_envelope(path, violations_log=tmp_path / "v.jsonl")


def test_generated_envelope_loads_and_covers_every_discovered_lane(tmp_path):
    env = _load(tmp_path)
    assert set(env.lanes()) == {"avara_2.0", "operator-brain", "dark-lane"}


def test_every_generated_ceiling_is_zero(tmp_path):
    """Provisioning describes the shape of authority; it never grants any."""
    env = _load(tmp_path)
    for name in env.lanes():
        assert env.ceiling_for(name) == 0.0, name


def test_named_money_lanes_bar_every_money_verb(tmp_path):
    env = _load(tmp_path)
    money = env.lane("avara_2.0")
    assert money.limits["money_touching"] is True
    for action in MONEY_IRREVERSIBLE:
        assert money.is_irreversible(action), action


def test_unnamed_lanes_are_still_restricted(tmp_path):
    """Unnamed means unsurveyed, not safe."""
    env = _load(tmp_path)
    other = env.lane("operator-brain")
    assert other.limits["money_touching"] is False
    for action in UNIVERSALLY_BARRED:
        assert other.is_irreversible(action), action
    assert other.is_irreversible("deploy")


def test_money_lanes_carry_a_higher_evidence_bar(tmp_path):
    env = _load(tmp_path)
    assert (env.lane("avara_2.0").min_crossings
            > env.lane("operator-brain").min_crossings)


def test_unmapped_blast_radius_is_recorded_in_the_config(tmp_path):
    """The reason a lane can never earn a ceiling stays visible in the file."""
    env = _load(tmp_path)
    dark = env.lane("dark-lane")
    assert dark.limits["blast_radius"] == "unmapped"
    assert dark.limits["ceiling_eligible"] is False


def test_defaulted_answers_still_produce_a_safe_envelope(tmp_path):
    """If the operator answered nothing, everything is treated as money."""
    env = _load(tmp_path, answers={"money_lanes": "all_treated_as_irreversible"})
    for name in env.lanes():
        lane = env.lane(name)
        assert lane.ceiling == 0.0
        for action in UNIVERSALLY_BARRED:
            assert lane.is_irreversible(action)


def test_a_perfect_record_still_buys_nothing_under_a_generated_envelope(tmp_path):
    env = _load(tmp_path)
    ledger = Ledger(tmp_path / "l.jsonl")
    for i in range(150):
        ledger.record_crossing(lane="avara_2.0", agent="x", scenario="observe",
                               crossing_id=f"c{i}", granted_multiplier=0.0,
                               originating_agent="a",
                               originating_envelope_digest=env.digest)
        ledger.grade(crossing_id=f"c{i}", lane="avara_2.0", agent="x",
                     outcome="success", originating_agent="a",
                     originating_envelope_digest=env.digest)
    denied = request_crossing(lane="avara_2.0", action="order_placement",
                              scenario="observe", originating_agent="a",
                              envelope=env, ledger=ledger, record=False)
    assert denied.granted is False
    exit_ok = request_crossing(lane="avara_2.0", action="abort",
                               scenario="observe", originating_agent="a",
                               envelope=env, ledger=ledger, record=False)
    assert exit_ok.granted is True and exit_ok.multiplier == 1.0


def test_generation_is_traceable_to_its_answers(tmp_path):
    text = build_envelope_yaml(scope=SCOPE, answers=ANSWERS, now=0.0)
    assert "GENERATED by drgb provisioning" in text
    assert "money_lanes=AVARA 2.0" in text
    assert "braid_sharing=share_attributed" in text


def test_refuses_to_clobber_a_hand_written_envelope(tmp_path):
    target = tmp_path / "hand.yaml"
    target.write_text("lanes:\n  mine:\n    ceiling: 0.0\n")
    with pytest.raises(ValueError):
        provision(scope=SCOPE, answers=ANSWERS, out_path=target)
    assert "mine" in target.read_text()          # untouched


def test_regenerating_its_own_output_is_allowed(tmp_path):
    target = tmp_path / "gen.yaml"
    provision(scope=SCOPE, answers=ANSWERS, out_path=target)
    provision(scope=SCOPE, answers=ANSWERS, out_path=target)   # no raise


def test_empty_scope_is_an_error_not_an_empty_envelope(tmp_path):
    with pytest.raises(ValueError):
        build_envelope_yaml(scope=_Scope([]), answers=ANSWERS)
