"""Turn interview answers into an authority envelope.

Without this the interview is a questionnaire nobody reads — the exact
failure mode this architecture was built after watching (producers with no
consumers). Answers must *become* configuration or they are theatre.

What it guarantees, regardless of what was answered:

* every generated ceiling is **0.0** — an install can never provision
  authority, only the shape authority would later take;
* lanes named as money/irreversible get the full irreversible set, permanently;
* lanes NOT named still get the same restrictions, because unnamed means
  unsurveyed, not safe;
* four actions are barred on every lane always: ``self_update``,
  ``credential_read``, ``envelope_edit``, ``grant_authority``;
* unmapped blast radius is recorded on the lane so the reason it can never
  earn a ceiling stays visible in the config itself.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Iterable

UNIVERSALLY_BARRED = ("self_update", "credential_read", "envelope_edit",
                      "grant_authority")

MONEY_IRREVERSIBLE = ("order_placement", "order_amend",
                      "order_cancel_and_replace", "withdrawal",
                      "offer_publish", "settlement_action", "key_rotation")

GENERAL_IRREVERSIBLE = ("service_enable", "service_disable", "deploy",
                        "dns_change", "force_push", "history_rewrite",
                        "outbound_message", "remote_execute")

DEFAULT_MIN_CROSSINGS = 50


def _parse_selection(value: str | None) -> set[str]:
    if not value or value in {"all_treated_as_irreversible", "none"}:
        return set()
    return {part.strip() for part in str(value).split(",") if part.strip()}


def _yaml_list(items: Iterable[str]) -> str:
    return "[" + ", ".join(sorted(set(items))) + "]"


def build_envelope_yaml(*, scope, answers: dict[str, str],
                        agent: str = "installer",
                        min_crossings: int = DEFAULT_MIN_CROSSINGS,
                        now: float | None = None) -> str:
    """Render an envelope from discovered lanes plus operator answers."""
    clock = float(now if now is not None else time.time())
    money = _parse_selection(answers.get("money_lanes"))
    lanes = list(getattr(scope, "lanes", []))
    if not lanes:
        raise ValueError("cannot provision an envelope with no discovered lanes")

    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(clock))
    header = [
        "# GENERATED by drgb provisioning — do not hand-edit without re-running",
        f"# generated_at: {stamp}",
        f"# generated_for: {agent}",
        f"# answers: money_lanes={answers.get('money_lanes', '(defaulted)')}"
        f" | braid_sharing={answers.get('braid_sharing', '(defaulted)')}",
        "#",
        "# EVERY ceiling is 0.0. Provisioning describes the SHAPE authority",
        "# would take; it never grants any. Raising a ceiling is an operator",
        "# act, made deliberately, outside any running process.",
        "",
        "lanes:",
    ]

    body: list[str] = []
    for lane in sorted(lanes, key=lambda c: c.name):
        is_money = lane.name in money
        irreversible = set(UNIVERSALLY_BARRED) | set(GENERAL_IRREVERSIBLE)
        if is_money:
            irreversible |= set(MONEY_IRREVERSIBLE)
        key = lane.name.replace(" ", "_").replace("/", "_").lower()
        body += [
            f"  {key}:",
            f"    scenarios_preapproved: [observe]",
            f"    ceiling: 0.0",
            f"    min_crossings: {min_crossings * (2 if is_money else 1)}",
            f"    out_of_sample_required: true",
            "    limits:",
            f"      source_lane: {lane.name!r}",
            f"      money_touching: {'true' if is_money else 'false'}",
            f"      blast_radius: {'mapped' if lane.ceiling_eligible else 'unmapped'}",
            f"      ceiling_eligible: {'true' if lane.ceiling_eligible else 'false'}",
            f"    irreversible_actions: {_yaml_list(irreversible)}",
        ]
    return "\n".join(header + body) + "\n"


def provision(*, scope, answers: dict[str, str], out_path: str | Path,
              agent: str = "installer", now: float | None = None) -> Path:
    """Write the generated envelope. Refuses to clobber a hand-written one."""
    p = Path(out_path)
    if p.exists():
        existing = p.read_text()
        if "GENERATED by drgb provisioning" not in existing:
            raise ValueError(
                f"refusing to overwrite a hand-written envelope: {p}")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(build_envelope_yaml(scope=scope, answers=answers,
                                     agent=agent, now=now))
    return p
